'''
    Various credentials for services KEEP uses.

    THIS FILE SHOULD NOT BE CHECKED INTO GIT
'''

# Amazon Web Services
# Key created May 8, 2012
AWS = {
    'ACCESS_KEY_ID': 'AKIAJNFVCEEAEVW7PXGQ',
    'SECRET_KEY': '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'
}

# Amazon RDS
RDS = {
    'HOST': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'USER': 'AAAAAAA',
    'PASSWORD': 'AAAAAAAAAAAAAAAA',
}
'''
MAILGUN = {
    'ACCESS_KEY': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'SERVER_NAME': 'AAAAAAAAAAAAAAAAAAAAAAAAAA',
}
'''

MAILGUN = {
    'ACCESS_KEY': 'key-2622hoeqt18f4qmfjo0z55e3p8bkqjl1',
    'SERVER_NAME': 'keep.distributedhealth.org',
}

FILEPICKER = {
    'API_KEY': 'AAAAAAAAAAAAAAAAAAAAAA',
}

RAVEN_CONFIG = {
    'dsn': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
}

SENTRY_KEY = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'

SECRET_KEY = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'

TWOFACTOR_ENCRYPTION_KEY = ''

